public class SymbolTable {
    public List<Constructors> constructors;
    public String id;
    public String key;
    public List<Method> methods;
    public String name;
    public List<TableDeclaration> tableDeclarations;
    public List<Variable> variables;
    public String parentClass;
    public List<String> interfaces;
    public List<Property> properties;
    public List<InnerClass> innerClasses;
}